# Generated by Django 6.0.2 on 2026-03-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getyourwebsite',
            new_name='getyourwebsitedata',
        ),
    ]
