# Generated by Django 6.0.2 on 2026-04-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_getyourwebsite_getyourwebsitedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getyourwebsitedata',
            name='budget_range',
            field=models.CharField(max_length=50),
        ),
    ]
